apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: dbaas-operators
spec:
  provisionerClassName: core-rukpak-io-plain
  template:
    metadata:
      labels:
        app: dbaas-operators
    spec:
      source:
        type: image
        image:
          ref: gen1us2k/dbaas-operators:latest
      provisionerClassName: core-rukpak-io-plain
